package com.example.contratistacompose.utils

const val EMAIL_CANNOT_EQUALS_PASSWORD = "Email and password cannot be the same"
const val PASSWORD_NOT_MATCH = "Password do not match"
const val UNEXPECTED_ERROR = "Unexpected error"
const val HIGH = "high"
const val REQUIRED = "Required"
const val EVENT_DATA = "Event data"
const val NOTE = "Note"
const val ENTER_ = "Enter "
const val DATE_FORMAT = "yyyy-MM-dd'T'HH:mm:ss.SSSXXX"
const val EXENTO = "Exento"
const val CUOTA = "Cuota"
const val TOTAL = "Total"
const val TOTALS = "Totals"
const val TOTAL_GAIN = "Total Gain"
const val ENTER_NOTE = "$ENTER_$NOTE please"
const val EDIT_NOTE = "edit_note"
const val LEGAL_NAME = "Legal name"
const val CUSTOMER_DATA = "Customer data"
const val TAX_IDENTIFICATION = "Tax identification"
const val FISCAL_REGIME = "Fiscal regime"
const val EMAIL = "Email"
const val PHONE = "Phone"
const val ADDRESS = "Address"
const val EXTERIOR = "Exterior"
const val INTERIOR = "Interior"
const val ADD_BUDGET = "Add budget"
const val BUDGET = "Budget"
const val DATE = "Date"
const val STATUS = "Status"
const val BUDGET_SECTION = "Budget Section"
const val PART_SECTION = "Part Section"
const val PRODUCT_SECTION = "Product Section"
const val FILTER_LIST = "Filter List"
const val BACK = "Back"
const val PART = "Part"
const val ADD_PART = "Add Part"
const val MONEY = "Money"
const val SAVE = "Save"
const val DELETE = "Delete"
const val TYPE = "Type"
const val CHANGE = "Change"
const val PRODUCT_SERVICE = "Product / Service"
const val PRODUCT_KEY = "Product Key"
const val QUANTITY = "Quantity"
const val DISCOUNT = "Discount"
const val SUB_TOTAL = "Sub Total"
const val UNIT = "Unit"
const val AMOUNT = "Amount"
const val SKU = "SKU"
const val TAX_INCLUDED = "Tax included"
const val TAX_NOT_INCLUDED = "Tax not included"
const val UNIT_NAME = "Unit Name"
const val OTHERS = "Others"
const val LOCAL_TAX = "Local Tax"
const val TAX = "Taxes"
const val PRICES = "Prices"
const val PRICE = "Price"
const val COST = "Cost"
const val COST_LIST = "Cost List"
const val GAIN_FOR_UNIT = "Gain for Unit"
const val AVAILABLE = "Available"
const val RESERVED = "Reserved"
const val INVENTORY = "Inventory"
const val MODIFIED = "Modified"
const val SELECT_PRODUCT = "Select Product"
fun getTaxability(value: String) = when (value) {
    "01" -> "No objeto de impuesto."
    "02" -> "Sí objeto de impuesto."
    "03" -> "Sí objeto de impuesto, pero no obligado a desglose."
    else -> "No objeto de impuesto."
}

// Password errors
const val MIN_MAX_LENGTH = "Password must be between 8 and 20 characters"
const val UPPERCASE = "Password must contain at least one uppercase letter"
const val LOWERCASE = "Password must contain at least one uppercase letter"
const val ONE_DIGIT = "Password must contain at least one digit"
const val ONE_SPECIAL_CHARACTER = "Password must contain at least one special character (@, #, \$, %)"
const val NO_WHITESPACE = "Password cannot contain whitespace"
const val THREE_CONSECUTIVE = "Password cannot contain more than 3 consecutive repeated characters"
const val NO_CONSECUTIVE = "Password cannot contain consecutive characters like 'abc', '123', etc."
const val NO_REPEATED_CHARACTER = "Password cannot contain repeated characters in sequence like '111', 'aaa', etc."


const val INVALID_EMAIL = "Invalid Email"
const val NO_LETTER_AND_SPECIAL_CHARACTER = "Only enter numbers"
const val IS_NOT_MONEY = "Enter decimal figures"
const val NO_NUMBER_AND_SPECIAL_CHARACTER = "Don´t enter numbers and special character"
const val NO_SPECIAL_CHARACTER = "Don´t enter special character"